name: Deploy a simple web application using github actions
on:
 push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: build docker image
        run: |
             docker build -t dinnu814/webapps:nginx-app_v1 .
    
      - name: fetch the list of docker images
        run: |
             docker images -a   

      - name: login to docker hub
        run: docker login {{vars.DOCKER_USERNAME}} {{ secrets.DOCKER_PASSWORD}}
          
             
      - name: push the docker image to docker hub
        run: |
             docker push dinnu814/webapps:nginx-app_v1
